language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules
    
# services: postgresql

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive
  - yarn global add codecov

script:
  - yarn test
  - yarn report
  - bash <(curl -s https://codecov.io/bash)